Bump org.springframework.boot:spring-boot-starter-parent from 4.0.0 to 4.0.1 (#145)
Bumps
[org.springframework.boot:spring-boot-starter-parent](https://github.com/spring-projects/spring-boot)
from 4.0.0 to 4.0.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-starter-parent's
releases</a>.</em></p>
<blockquote>
<h2>v4.0.1</h2>
<h2>:warning: Noteworthy changes</h2>
<ul>
<li>Hibernate has been upgraded to 7.2.0.Final in response to Hibernate
7.1 moving to limited support</li>
<li>spring-boot-starter-kotlin-serialization has been renamed to to
spring-boot-starter-kotlinx-serialization-json and
spring-boot-starter-kotlin-serialization-test has been renamed to
spring-boot-starter-kotlinx-serialization-json-test. This change aligns
the starters' names with those of their respective modules</li>
<li>Using TestRestTemplate now <a
href="https://docs.spring.io/spring-boot/4.0-SNAPSHOT/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.with-running-server">requires
a dependency on spring-boot-restclient</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>JsonMixinModuleEntriesBeanRegistrationAotProcessor does not handle
deprecated code <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48564">#48564</a></li>
<li>JdbcSessionAutoConfiguration may not match when using the
auto-configured DataSource <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48552">#48552</a></li>
<li><code>@ServiceConnection</code> for LgtmStackContainer fails when
logging endpoint is configured due to multiple
OtlpLoggingConnectionDetails beans <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48536">#48536</a></li>
<li>WebApplicationType does not consider modules when deduced from
classpath <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48517">#48517</a></li>
<li>Spring Session auto-configuration fails in a war deployment as
ServerProperties is not available <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48493">#48493</a></li>
<li>Opentelemetry logging export requires actuator module <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48488">#48488</a></li>
<li>RabbitHealthIndicator reports an error when version is missing from
the connection's server properties <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48487">#48487</a></li>
<li>Actuator Info class has inconsistent nullability annotations and
cannot be built with null value <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48480">#48480</a></li>
<li>Profiles retained during AOT processing are not configured in a
native image <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48476">#48476</a></li>
<li>Security matchers and WebServerNamespace resolution can fail with
NoClassDefFoundError when used in a traditional WAR deployment <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48388">#48388</a></li>
<li>HealthEndpointGroupMembershipValidator does not consider reactive
health indicators causing NoSuchHealthContributorException to be thrown
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48387">#48387</a></li>
<li>spring.jackson.default-property-inclusion is not applied to content
inclusion <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48343">#48343</a></li>
<li>TestRestTemplate.getRootUri() returns empty string <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48330">#48330</a></li>
<li>Redis health check reports an error when redis_version is missing
from the INFO response <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48328">#48328</a></li>
<li>Parent's MeterRegistry beans are closed when child context closes <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48325">#48325</a></li>
<li>HttpMessageConverters picks up converter beans for both client and
server <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48310">#48310</a></li>
<li>Conditions to auto-configure a RestClient are outdated with the
modularization <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48308">#48308</a></li>
<li>A custom JwtTypeValidator that replaces the default can no longer be
configured <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48301">#48301</a></li>
<li>PropertiesRestClientHttpServiceGroupConfigurer has highest
precedence, preventing other configurers from being ordered ahead of it
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48296">#48296</a></li>
<li>SpringBootTest.UseMainMethod.WHEN_AVAILABLE and ALWAYS are
incompatible with package-private or parameter-less main method <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48275">#48275</a></li>
<li>Conditions to auto-configure RestClient-based HTTP service clients
are outdated with the modularization <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48274">#48274</a></li>
<li>Starter for Kotlinx Serialization Json is misnamed <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48262">#48262</a></li>
<li>ApplicationServletEnvironment is no longer configured in war
deployments <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48254">#48254</a></li>
<li>RestClient.Builder bean present in <code>@SpringBootTest</code> due
to spring-boot-starter-webmvc-test, but missing at runtime without
restclient starter <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48253">#48253</a></li>
<li>ProblemDetail is rendered to XML incorrectly <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48222">#48222</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Harmonize Kotlin example for HTTP Service client support <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48577">#48577</a></li>
<li>Document HttpMessageConverters detection changes in 4.0.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48574">#48574</a></li>
<li>Improve javadoc for when to use class names rather than class
references <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48569">#48569</a></li>
<li>Documentation has an outdated reference to the Jackson Kotlin Module
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48534">#48534</a></li>
<li>Caching documentation should clarify how to use a no-op
implementation to run a test suite <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48532">#48532</a></li>
<li>Document that the default rolling policy for Log4j2 requires
logging.file.path to be set <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48527">#48527</a></li>
<li>Review documentation and migration guide about changes in
<code>@AutoConfigureCache</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48522">#48522</a></li>
<li>License header in build samples is displayed in the reference
documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48478">#48478</a></li>
<li>Configuring Two DataSources How-To code sample is inconsistent <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48449">#48449</a></li>
<li>Fix links to source files on GitHub <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48398">#48398</a></li>
<li>Documentation contains broken links to GitHub source files <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48394">#48394</a></li>
<li>Document that org.aspectj.weaver.Advice must be on the classpath to
enable support for Micrometer's annotations <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48360">#48360</a></li>
<li>Correct the annotation in the Kotlin
<code>@ConfigurationPropertiesSource</code> example <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/48357">#48357</a></li>
<li>Polish TestRestTemplate examples in the reference guide <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48336">#48336</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b2bc463d997df6f1b9eba8aaa1f7c2b38fb6f012"><code>b2bc463</code></a>
Release v4.0.1</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/252b218ac946abf2ac5dedfca580d5d828c5c17c"><code>252b218</code></a>
Correct renaming of Kotlinx Serialization JSON starters</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/2fa73c27ef3dee11942ca7c3b7be5e1129e6d161"><code>2fa73c2</code></a>
Merge pull request <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/48577">#48577</a>
from jwalter</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/3e689881f2580c635084e7023b91b64582627647"><code>3e68988</code></a>
Polish &quot;Harmonize Kotlin example for HTTP Service client
support&quot;</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/423373ba06ce604faa5cd0aa5b41887a27b9cd64"><code>423373b</code></a>
Harmonize Kotlin example for HTTP Service client support</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f61ac29f3ffdcfea7535bd882ec0daefdd9057f9"><code>f61ac29</code></a>
Document HttpMessageConverters detection changes</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/2519a5d2aec41cd3bedc4ff0d1da0bc4658df404"><code>2519a5d</code></a>
Merge branch '3.5.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/4fc3ca35962c2ed7182eee32e70457d787ac74ab"><code>4fc3ca3</code></a>
Next development version (v3.5.10-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/aaf66f4d500121960e680f3e415912adf4f8d7b6"><code>aaf66f4</code></a>
Merge branch '3.5.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/08e2cab6b0aedd9ffa8536b9725cd809f4793df7"><code>08e2cab</code></a>
Polish javadoc for when to use class names rather than class
references</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v4.0.0...v4.0.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-starter-parent&package-manager=maven&previous-version=4.0.0&new-version=4.0.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: lelsaesser <lucas.elsaesser@gmail.com>